exclude: ^(?!.*[.]py$).*$
repos:
-   repo: local
    hooks:
    - id: isort
      name: isort
      entry: isort
      language: system
      types: [python]
      stages: [commit]
      args:
        - --line-length=120
        - --use-parentheses
        - --trailing-comma
        - --multi-line=3

    - id: black
      name: black
      language: system
      entry: black
      types: [python]
      stages: [commit]
      args:
        - --line-length=120

    - id: flake8
      name: flake8
      language: system
      entry: flake8
      types: [python]
      stages: [commit]
      args:
        - --max-line-length=120
    - id: mypy
      name: mypy
      language: system
      entry: mypy
      types: [python]
      stages: [commit]
      args:
        - --strict
        - --ignore-missing-imports
